import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import UnhandledRejectionGuard from "../components/UnhandledRejectionGuard";
import { CartProvider } from "../context/cart";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CartProvider>
          {/* inline guard to prevent noisy failed fetches from external analytics (runs before client JS) */}
          <script dangerouslySetInnerHTML={{__html: `(function(){try{if(typeof window==='undefined')return;var o=window.fetch.bind(window);window.fetch=function(i,u){try{return o(i,u).catch(function(err){try{var url=typeof i==='string'?i:(i&&i.url?i.url:'');if(url&& (url.indexOf('fullstory')!==-1 || url.indexOf('fullstory.com')!==-1)){return new Response(null,{status:503,statusText:'Service Unavailable'});} }catch(e){} throw err;});}catch(e){return o(i,u);} };}catch(e){} })();`}} />

          <Navbar />
          <UnhandledRejectionGuard />
          <main>{children}</main>

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
